# Generated by Django 4.2.20 on 2025-04-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CodeScanReport',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
